### ISSUE TITLE
Display it on yunohost.org/apps

### ISSUE THREAD

**Issue by nicofrand** [YunoHost-Apps/laverna_ynh#1]
See https://github.com/YunoHost/apps/pull/149.
The previous developper is OK with it, so if this version is working as expected, you could maybe make it the one listed on yunohost.org/apps ?

**Comment by anaqreon** [comment]
I have no problem with putting the app on the official list if it works. As I said in an email recently, I should no longer be part of the Laverna team, since I do not use this app and do not maintain it.
